Controllers/AuthorController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;

        public AuthorController(IAuthorService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Authors()
        {
            var allAuthor = await _service.GetAllAsync();
            return View(allAuthor);
        }

        //GET
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, LogoUrl, Experience")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.AddAsync(author);
            return RedirectToAction(nameof(Authors));
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, LogoUrl, Experience")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.UpdateAsync(id, author);
            return RedirectToAction(nameof(Authors));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Authors));
        }
    }
}

Controllers/CompanyController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _service;

        public CompanyController(ICompanyService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Companies()
        {
            var result = await _service.GetAllAsync();
            return View(result);
        }

        //GET
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, LogoUrl, Description")] Company company)
        {
            if (!ModelState.IsValid)
            {
                return View(company);
            }
            await _service.AddAsync(company);
            return RedirectToAction(nameof(Companies));
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, LogoUrl, Description")] Company company)
        {
            if (!ModelState.IsValid)
            {
                return View(company);
            }
            await _service.UpdateAsync(id, company);
            return RedirectToAction(nameof(Companies));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Companies));
        }
    }
}

Controllers/CourseController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CourseController : Controller
    {
        private readonly ICourseService _service;

        public CourseController(ICourseService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Courses()
        {
            var result = await _service.GetAllAsync(c => c.Company);
            return View(result);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var result = await _service.GetAllAsync(c => c.Company);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = result.Where(c => c.Name.ToLower().Contains(searchString.ToLower()) || c.Description.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Courses", filteredResult);
            }

            return View("Courses", result);
        }

        //GET
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetCourseByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public async Task<IActionResult> Create()
        {
            var result = await _service.GetCoursesDropDownListVM();

            ViewBag.Companies = new SelectList(result.Companies, "Id", "Name");
            ViewBag.Authors = new SelectList(result.Authors, "Id", "FullName");
            ViewBag.Teachers = new SelectList(result.Teachers, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseVM course)
        {
            if (!ModelState.IsValid)
            {
                var result = await _service.GetCoursesDropDownListVM();

                ViewBag.Companies = new SelectList(result.Companies, "Id", "Name");
                ViewBag.Authors = new SelectList(result.Authors, "Id", "FullName");
                ViewBag.Teachers = new SelectList(result.Teachers, "Id", "FullName");

                return View(course);
            }
            await _service.AddNewCourseAsync(course);
            return RedirectToAction(nameof(Courses));
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var ditails = await _service.GetCourseByIdAsync(id);
            if (ditails == null) return View("NotFound");

            var response = new CourseVM()
            {
                Id = ditails.Id,
                Name = ditails.Name,
                Description = ditails.Description,
                Price = ditails.Price,
                LogoUrl = ditails.LogoUrl,
                StartDate = ditails.StartDate,
                EndDate = ditails.EndDate,
                CourseCategory = ditails.CourseCategory,
                CompanyId = ditails.CompanyId,
                AuthorId = ditails.AuthorId,
                TeacherIds = ditails.Teachers_Courses.Select(t => t.TeatherId).ToList()
            };

            var dropDown = await _service.GetCoursesDropDownListVM();
            ViewBag.Companies = new SelectList(dropDown.Companies, "Id", "Name");
            ViewBag.Authors = new SelectList(dropDown.Authors, "Id", "FullName");
            ViewBag.Teachers = new SelectList(dropDown.Teachers, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CourseVM course)
        {
            if (id != course.Id)
            {
                return View("NotFound");
            }
            
            if (!ModelState.IsValid)
            {
                var result = await _service.GetCoursesDropDownListVM();

                ViewBag.Companies = new SelectList(result.Companies, "Id", "Name");
                ViewBag.Authors = new SelectList(result.Authors, "Id", "FullName");
                ViewBag.Teachers = new SelectList(result.Teachers, "Id", "FullName");

                return View(course);
            }
            await _service.UpdateCourseAsync(course);
            return RedirectToAction(nameof(Courses));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Courses));
        }
    }
}

Controllers/OrderController.cs
using eTutorials.Data.Cart;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;
        public OrderController(ICourseService courseService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _courseService = courseService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> ListOfOrders()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrderByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult Orders()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()

            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _courseService.GetCourseByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _courseService.GetCourseByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmail);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrserCompleted");
        }
    }
}

Views/Shared/NotFound.cshtml
<div class="row text-black-50 text-center text-capitalize">
    <div class="col-md-2 offset-5">
        <h1>Never existed!</h1>
        <hr />
        <a class="btn btn-outline-secondary" asp-action="Teachers" asp-controller="Teacher">Go back! And try again!</a>
    </div>    
</div>

Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed; right:70px; bottom:70px" class="text-white-70">
        <a asp-action="Create" asp-controller="@Model" class="btn btn-success"><i class="bi bi-plus-circle"></i> Add </a>
    </div>
}

Views/Shared/_Identity.cshtml
@inject UserManager<AppUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-3 my-sm-2" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Enter 
    </a>
    <span style="padding:5px;"></span>

    <a class="btn btn-outline-primary my-3 my-sm-2" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus-fill"></i> Create new Account
    </a>
    <span style="padding:5px;"></span>
}
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle"></i> Hi @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Order" asp-action="ListOfOrders" style="text-align:left"><i class="bi bi-card-checklist"></i>   Orders</a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users" style="text-align:left"><i class="bi bi-people"></i>   Users</a>
                </li>
            }

        </ul>
    </div>

    <span style="padding:5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-3 my-sm-2">
            <i class="bi bi-box-arrow-in-right"></i> Exit
        </button>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTutorials</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-md-4">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Course" asp-action="Courses" style="text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue; color: white;">Tutorials</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <div class="row col-md-5 offset-3">
                                    <a class="nav-pills dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-list"></i> Menu
                                    </a>

                                    <div class="dropdown-menu" labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Company" asp-action="Companies"><i class="bi bi-building"></i> Companies</a>
                                        <a class="dropdown-item" asp-controller="Author" asp-action="Authors"><i class="bi bi-person"></i> Authors</a>
                                        <a class="dropdown-item" asp-controller="Teacher" asp-action="Teachers"><i class="bi bi-person"></i> Teachers</a>
                                    </div>
                                </div>
                            </li>
                        }


                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Course" asp-action="Filter" style="padding-right: 75px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a course..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <span style="padding:5px;"></span>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSumBar")
                    </ul>

                    <partial name="_Identity.cshtml" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container offset-5">
            &copy; @DateTime.Now.Year - Tutorials. By with us - we have some class!
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>