Models/Course.cs
using eTutorials.Data;
using eTutorials.Data.Repositories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Models
{
    public class Course : IEntityForRepo
    {
        [Key]
        public int Id { get; set; }
        public string LogoUrl { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public CourseCategory CourseCategory { get; set; }

        //Relations
        public List<Teacher_Course> Teachers_Courses { get; set; }

        public int CompanyId { get; set; }
        [ForeignKey("CompanyId")]
        public Company Company { get; set; }

        public int AuthorId { get; set; }
        [ForeignKey("AuthorId")]
        public Author Author { get; set; }
    }
}

Controllers/AuthorController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;

        public AuthorController(IAuthorService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Authors()
        {
            var allAuthor = await _service.GetAllAsync();
            return View(allAuthor);
        }

        //GET
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, LogoUrl, Experience")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.AddAsync(author);
            return RedirectToAction(nameof(Authors));
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, LogoUrl, Experience")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.UpdateAsync(id, author);
            return RedirectToAction(nameof(Authors));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Authors));
        }
    }
}

Controllers/CompanyController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _service;

        public CompanyController(ICompanyService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Companies()
        {
            var result = await _service.GetAllAsync();
            return View(result);
        }

        //GET
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, LogoUrl, Description")] Company company)
        {
            if (!ModelState.IsValid)
            {
                return View(company);
            }
            await _service.AddAsync(company);
            return RedirectToAction(nameof(Companies));
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, LogoUrl, Description")] Company company)
        {
            if (!ModelState.IsValid)
            {
                return View(company);
            }
            await _service.UpdateAsync(id, company);
            return RedirectToAction(nameof(Companies));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Companies));
        }
    }
}

Controllers/CourseController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CourseController : Controller
    {
        private readonly ICourseService _service;

        public CourseController(ICourseService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Courses()
        {
            var result = await _service.GetAllAsync(c => c.Company);
            return View(result);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var result = await _service.GetAllAsync(c => c.Company);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = result.Where(c => c.Name.ToLower().Contains(searchString.ToLower()) || c.Description.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Courses", filteredResult);
            }

            return View("Courses", result);
        }

        //GET
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetCourseByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public async Task<IActionResult> Create()
        {
            var result = await _service.GetCoursesDropDownListVM();

            ViewBag.Companies = new SelectList(result.Companies, "Id", "Name");
            ViewBag.Authors = new SelectList(result.Authors, "Id", "FullName");
            ViewBag.Teachers = new SelectList(result.Teachers, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseVM course)
        {
            if (!ModelState.IsValid)
            {
                var result = await _service.GetCoursesDropDownListVM();

                ViewBag.Companies = new SelectList(result.Companies, "Id", "Name");
                ViewBag.Authors = new SelectList(result.Authors, "Id", "FullName");
                ViewBag.Teachers = new SelectList(result.Teachers, "Id", "FullName");

                return View(course);
            }
            await _service.AddNewCourseAsync(course);
            return RedirectToAction(nameof(Courses));
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var ditails = await _service.GetCourseByIdAsync(id);
            if (ditails == null) return View("NotFound");

            var response = new CourseVM()
            {
                Id = ditails.Id,
                Name = ditails.Name,
                Description = ditails.Description,
                Price = ditails.Price,
                LogoUrl = ditails.LogoUrl,
                StartDate = ditails.StartDate,
                EndDate = ditails.EndDate,
                CourseCategory = ditails.CourseCategory,
                CompanyId = ditails.CompanyId,
                AuthorId = ditails.AuthorId,
                TeacherIds = ditails.Teachers_Courses.Select(t => t.TeatherId).ToList()
            };

            var dropDown = await _service.GetCoursesDropDownListVM();
            ViewBag.Companies = new SelectList(dropDown.Companies, "Id", "Name");
            ViewBag.Authors = new SelectList(dropDown.Authors, "Id", "FullName");
            ViewBag.Teachers = new SelectList(dropDown.Teachers, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CourseVM course)
        {
            if (id != course.Id)
            {
                return View("NotFound");
            }
            
            if (!ModelState.IsValid)
            {
                var result = await _service.GetCoursesDropDownListVM();

                ViewBag.Companies = new SelectList(result.Companies, "Id", "Name");
                ViewBag.Authors = new SelectList(result.Authors, "Id", "FullName");
                ViewBag.Teachers = new SelectList(result.Teachers, "Id", "FullName");

                return View(course);
            }
            await _service.UpdateCourseAsync(course);
            return RedirectToAction(nameof(Courses));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Courses));
        }
    }
}

Controllers/OrderController.cs
using eTutorials.Data.Cart;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;
        public OrderController(ICourseService courseService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _courseService = courseService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> ListOfOrders()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrderByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult Orders()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()

            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _courseService.GetCourseByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _courseService.GetCourseByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmail);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrserCompleted");
        }
    }
}

Controllers/TeacherController.cs
using eTutorials.Data;
using eTutorials.Data.Services;
using eTutorials.Data.StaticClasses;
using eTutorials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTutorials.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class TeacherController : Controller
    {
        private readonly ITeacherService _service;

        public TeacherController(ITeacherService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Teachers()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        
        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, LogoUrl, Experience")]Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }
            await _service.AddAsync(teacher);
            return RedirectToAction(nameof(Teachers));            
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        //GET
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, LogoUrl, Experience")] Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }
            await _service.UpdateAsync(id, teacher);
            return RedirectToAction(nameof(Teachers));
        }

        //GET
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Teachers));
        }
    }
}

Views/Course/Courses.cshtml
@model IEnumerable<Course>

@{
    ViewData["Title"] = "A list of Courses:";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-secondary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-primary">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.LogoUrl" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><h5>@item.Description</h5></p>
                            <p class="card-text"><b>Company: </b>@item.Company.Name</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-warning text-black">GOING</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">STARTING SOON</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-info-circle-fill"></i> More about
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                                   asp-controller="Order"
                                   asp-action="AddItemToShoppingCart"
                                   asp-route-id="@item.Id">                                    
                                    <i class="bi bi-cart3"></i> Buy for: @item.Price.ToString("C", new System.Globalization.CultureInfo("en-US"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Course")

Views/Course/Create.cshtml
@model CourseVM
@using eTutorials.Data;

@{ 
    ViewData["Title"] = "Create new Course";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h3>Create a Course</h3>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">

                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LogoUrl" class="control-label"></label>
                                <input asp-for="LogoUrl" class="form-control" />
                                <span asp-validation-for="LogoUrl" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CompanyId" class="control-label"></label>
                                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companies"></select>
                                <span asp-validation-for="CompanyId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CourseCategory" class="control-label"></label>
                                <select asp-for="CourseCategory" class="form-control" asp-items="Html.GetEnumSelectList<CourseCategory>()"></select>
                                <span asp-validation-for="CourseCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AuthorId" class="control-label"></label>
                                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.Authors"></select>
                                <span asp-validation-for="AuthorId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="TeacherIds" class="control-label"></label>
                                <select asp-for="TeacherIds" class="form-control" asp-items="ViewBag.Teachers" multiple></select>
                                <span asp-validation-for="TeacherIds" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>

                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="LogoUrlPreview"/>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Courses">Show All</a>
                    </div>

                </form>

            </div>
        </div>

    </div>    
</div>

@section Scripts{ 
    <script>
        $("#LogoUrl").on("change", function () {
            var output = document.getElementById("LogoUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Views/Course/Details.cshtml
@model Course

@{
    ViewData["Title"] = "The Course:";
}

<div class="row">
    
        <div class="col-md-9 offset-4">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-primary">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @Model.Name
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="@Model.LogoUrl" width="100%" alt="@Model.Name">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text"><h5>@Model.Description</h5></p>
                            <p class="card-text">
                                <b>Company: </b>
                                <a asp-action="Details" asp-controller="Company" asp-route-id="@Model.CompanyId">@Model.Company.Name</a>
                            </p>
                            <p class="card-text">
                                <b>Author: </b>@Model.AuthorId
                                <a asp-action="Details" asp-controller="Author" asp-route-id="@Model.AuthorId">@Model.Author.FullName</a>
                            </p>
                            <p class="card-text"><b>Category: </b>@Model.CourseCategory</p>
                            <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                                {
                                    <span class="badge bg-success text-white">GOING</span>
                                }
                                else if (DateTime.Now > Model.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">STARTING SOON</span>
                                }
                            </p>

                            <p class="card-text">
                                <b>Teachers:</b>
                                <hr />
                                <div class="row">
                                    @foreach (var item in Model.Teachers_Courses)
                                    {
                                    <div class="colomn text-center">
                                        <img class="border-info rounded-circle" src="@item.Teacher.LogoUrl" style="max-width:175px" alt="@item.Teacher.FullName" />
                                        <br />
                                        <a asp-action="Details" asp-controller="Teacher" asp-route-id="@item.TeatherId">@item.Teacher.FullName</a>
                                    </div>
                                    }
                                </div>
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Courses">
                                    Back to list.
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > Model.EndDate) ? "disabled" : "")"
                                   asp-controller="Order"
                                   asp-action="AddItemToShoppingCart"
                                   asp-route-id="@Model.Id">
                                    <i class="bi bi-cart3"></i> Buy for: @Model.Price.ToString("C", new System.Globalization.CultureInfo("en-US"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>